### ISSUE TITLE
OSError: Error relocating .... unsupported relocation type 1026

### ISSUE THREAD

**Issue by Di1Ly** [keith-kl/homeassistant-lampsmartpro#1]
Hi! Thanx for your integration.
I have error like blelow.
Sould I compile liblampify.so according to my HA platform Generic x86-64 ?
Or ?

Logger: homeassistant.components.light
Source: custom_components/lampsmartpro/lampsmartpro.py:9
Integration: light (documentation, issues)
First occurred: 20:34:16 (1 occurrences)
Last logged: 20:34:16

Error while setting up lampsmartpro platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/lampsmartpro/light.py", line 42, in setup_platform
    api = LampSmartProAPI()
  File "/config/custom_components/lampsmartpro/lampsmartpro.py", line 9, in __init__
    self._libLamp = CDLL(self._so_file)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error relocating /config/custom_components/lampsmartpro/liblampify.so: unsupported relocation type 1026

**Comment by keith-kl** [comment]
Hi,

Yes I compile the shared library in my Raspberry pi so it might not work in your HA. I have forked a version from the original author (https://github.com/keith-kl/liblampify) so you may try to compile yours.
